### ISSUE TITLE
Monarch Ontology Review

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-ontology#28]
# Step 1: Monarch Ontology Review: SIGNATURE

Because the diff is huge, to big to be proberly reviewed, I will portion it for you @cmungall @kshefchek 

This here is a breakdown of the big blocks of missing IRIs in the signature. I only just made the list, without trying to understand it. The following table is a breakdown of all the namespaces that have more than 20 unique IRIs which are **missing from the new ODK built of Monarch.owl,** and the goal is to find out why that is. There are currently 337,348 entities declared in the old monarch.owl, and 221,631 in the new, ODK-based. Prima facie reasons you need to consider when interpreting this:

1) CHEBI and GO are IMPORTS, not COMPONENTS. That means they are only imported insofar that another ontology uses them.
2) Bases are used in some cases (not often enough yet)

Namespace | # missing classes
-- | --
http://purl.obolibrary.org/obo/GO | 38950
http://purl.obolibrary.org/obo/CHEBI | 20384
http://linkedlifedata.com/resource/umls/id | 14030
http://purl.obolibrary.org/obo/NCBITaxon | 13214
http://www.orpha.net/ORDO/Orphanet | 9077
http://purl.obolibrary.org/obo/SCTID | 9001
http://omim.org/entry | 8338
http://purl.obolibrary.org/obo/DOID | 8294
http://purl.obolibrary.org/obo/NCIT | 6781
http://purl.obolibrary.org/obo/FMA | 6495
http://purl.obolibrary.org/obo/GARD | 5820
http://purl.obolibrary.org/obo/MESH | 4776
http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id | 3743
http://purl.obolibrary.org/obo/MA | 3071
http://www.ebi.ac.uk/efo/EFO | 2826
http://linkedlifedata.com/resource/umls/id/C | 2588
http://purl.obolibrary.org/obo/PATO | 1648
http://purl.obolibrary.org/obo/COHD | 1592
http://purl.obolibrary.org/obo/UBERO | 1241
http://purl.obolibrary.org/obo/GOCHE | 851
http://purl.obolibrary.org/obo/CL | 771
http://purl.obolibrary.org/obo/OBI | 623
http://www.omim.org/phenotypicSeries/P | 425
http://purl.obolibrary.org/obo/PR | 322
http://purl.obolibrary.org/obo/PO | 269
http://purl.obolibrary.org/obo/D | 153
http://purl.obolibrary.org/obo/OBA | 104
http://purl.obolibrary.org/obo/ENVO | 91
http://purl.obolibrary.org/obo/FOODON | 86
http://purl.obolibrary.org/obo/UO | 62
http://purl.obolibrary.org/obo/ICD9 | 42
http://purl.obolibrary.org/obo/KEGG | 34
http://purl.obolibrary.org/obo/FAO | 31

Here, for your reference, the currently configured sets of imports:

```
import_group:
  products:
    - id: nbo
      mirror_from: http://purl.obolibrary.org/obo/nbo/nbo-base.owl
    - id: go
      mirror_from: http://current.geneontology.org/ontology/go-base.owl
    - id: fao
    - id: oba
    - id: po
    - id: vt
    - id: stato
    - id: bfo
    - id: chebi
      mirror_from: http://purl.obolibrary.org/obo/chebi.owl.gz
    - id: hsapdv
    - id: cl
      mirror_from: http://purl.obolibrary.org/obo/cl/cl-base.owl
    - id: mpath
    - id: ncbitaxon-taxslim
      mirror_from: http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl
    - id: go-plus
      mirror_from: http://purl.obolibrary.org/obo/go/extensions/go-plus.owl
    - id: caro
    - id: pato
    - id: uberon-ext
      mirror_from: http://purl.obolibrary.org/obo/uberon/ext.owl
    - id: uberon-bridge-to-zfa
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa.owl
    - id: uberon-bridge-to-ma
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-ma.owl
    - id: uberon-bridge-to-wbbt
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-wbbt.owl
    - id: uberon-bridge-to-fbbt
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-fbbt.owl
    - id: uberon-bridge-to-fma
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-fma.owl
    - id: uberon-bridge-to-nifstd
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-nifstd.owl
    - id: cl-bridge-to-ma
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-ma.owl
    - id: cl-bridge-to-fma
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-fma.owl
    - id: cl-bridge-to-wbbt
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-wbbt.owl
    - id: cl-bridge-to-fbbt
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-fbbt.owl
    - id: cl-bridge-to-zfa
      mirror_from: http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-zfa.owl
components:
  products:
    - filename: upheno.owl
      source: https://raw.githubusercontent.com/obophenotype/upheno/master/metazoa.owl
    - filename: mondo.owl
      source: http://purl.obolibrary.org/obo/mondo/mondo-base.owl
    - filename: eco.owl
      source: http://purl.obolibrary.org/obo/eco/eco-base.owl
    - filename: so.owl
    - filename: geno.owl
    - filename: sepio.owl
    - filename: ro.owl
    - filename: clo.owl
    - filename: uberon.owl
      source: http://purl.obolibrary.org/obo/uberon/uberon-base.owl
    - filename: ncit.owl
    - filename: fbbt.owl
      source: http://purl.obolibrary.org/obo/fbbt/fbbt-base.owl
    - filename: wbbt.owl
      source: http://purl.obolibrary.org/obo/wbbt/wbbt-base.owl
    - filename: ecto.owl
      source: http://purl.obolibrary.org/obo/ecto/ecto-base.owl
    - filename: zfa.owl
      source: http://purl.obolibrary.org/obo/zfa/zfa-base.owl
    - filename: maxo.owl
      source: http://purl.obolibrary.org/obo/maxo/maxo-base.owl
```

My assumption is that @cmungall will suggest to import GO and CHEBI as a hole (components) rather than SLME modules.
